# Indexing 2d array(matrices)


In [1]:
import numpy as np

In [2]:
arr_2d=np.array(([1,2,3],[4,5,6],[7,8,9],[2,6,8]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 6, 8]])

In [3]:
arr_2d[2] #gives index of row

array([7, 8, 9])

In [6]:
arr_2d[2,2]     #value which place row and col

9

In [9]:
arr_2d[[2,1]]    #multiple rows

array([[7, 8, 9],
       [4, 5, 6]])

In [13]:
arr_2d[2][2]

9

In [5]:
#for reverse indexing
import numpy as np
a=np.arange(10)
a
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
#indexing multiple rows ( : gives range of rows)
arr_2d[2:4]

array([[7, 8, 9],
       [2, 6, 8]])

In [22]:
#to getting individual array
arr_2d[2,0] #1st value for row and  2nd value for col they separetaed by , 

7

In [15]:
#2d array slicing
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [16]:
arr_2d=np.arange(16).reshape(4,4)
arr_2d[2:4][1:2]

array([[12, 13, 14, 15]])

#  selection

In [9]:
arr1=np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [10]:
arr1>6

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [11]:
arr1[arr1>6]    # if you want actual value give condition into square  bracket

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [12]:
arr1[arr1==12]

array([12])

In [13]:
arr1[(arr1!=16)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18,
       19, 20])

# np. where

In [14]:
np.where(arr1>7)  # indices

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)

In [15]:
arr1[np.where(arr1>7)]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
#case2                    #on the place of 1 you can put any number
np.where(arr1>7,arr1,1)

array([ 1,  1,  1,  1,  1,  1,  1,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
np.where(arr1>4,arr1,2)

array([ 2,  2,  2,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])