In [1]:
#what is numpy-numeric python package that provide multi dimensional array

In [2]:
import numpy as np

In [3]:
#using array
Distance=[100,70,60,80]
Time=[7,8,9,10]
Distance_Arr=np.array(Distance)
Time_Arr=np.array(Time)
speed=Distance_Arr/Time_Arr
speed

array([14.28571429,  8.75      ,  6.66666667,  8.        ])

In [4]:
type(speed)

numpy.ndarray

In [5]:
%%time
ls=list(range(1,100,5))
for i in range(1,100,5):
    ls1=i+5
    print(ls1)

6
11
16
21
26
31
36
41
46
51
56
61
66
71
76
81
86
91
96
101
CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
%%time
ls=np.arange(1,100,5)
print(ls)
ar=ls+5
print(ar)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[  6  11  16  21  26  31  36  41  46  51  56  61  66  71  76  81  86  91
  96 101]
CPU times: total: 0 ns
Wall time: 2.15 ms


# 1. Time

In [7]:
import random

In [8]:
%%time                                #numpy
for i in range(1000):
    a=np.arange(1,1000,3)
    b=np.arange(2,1001,3)
    c=a+b
  

UsageError: Can't use statement directly after '%%time'!


In [ ]:
%%time                                                  #python
for j in range(1000):
    ls1=list(range(1,1000,3))
    ls2=list(range(2,1001,3))
    ls3=[]
    for i in range(len(ls1)):
        ls3.append(ls1[i]+ls2[i])
        #print(ls3)

# 2. Memory

In [ ]:
#it is use to check memory sys is use for size
import sys
py_ls=[100,90,80,70,60]
numpy_ls=np.array([50,40,30,20])

sizeof_pyls=sys.getsizeof(1)*len(py_ls)
sizeof_numpyls=numpy_ls.itemsize * numpy_ls.size

print("size of python list",sizeof_pyls)
print("size of numpy list",sizeof_numpyls)


In [ ]:
%%time
import numpy as np
ls_n= np.array([[100, 20, 34],
             [300, 400, 600]])
size_x=ls_n.itemsize * ls_n.size
print("size of list : ",size_x)

# 3.Numpy arrays
## Generation Of Numpy array Using List


In [9]:
#1d matrix
ls=[10,20,30]
print(ls)

[10, 20, 30]


In [10]:
print(type(ls))

<class 'list'>


In [11]:
np.array(ls)


array([10, 20, 30])

In [12]:
#2d matrix
matrix1=[[10,20,30],[40,50,60],[70,80,90]]
matrix1

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [13]:
#multiple ways to create matrix

In [14]:
#1 using array - we can do internal addition into array it give proper access
np.array(matrix1)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# Generation of numpy array using built in functions

In [15]:
#it is simmilar to range()
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [16]:
np.arange(1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [17]:
np.arange(1,20,-1)

array([], dtype=int32)

In [18]:
np.arange(-20,1,-1)

array([], dtype=int32)

In [19]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Generate arrays on zeros and ones

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Linspace- it distributes equally

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

# EYE- It gives identity matrix

In [26]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Generate random number
# rand it give random value between (0-1)

In [28]:
np.random.rand(5)

array([0.90997111, 0.72166028, 0.83660504, 0.39663096, 0.97669641])

In [29]:
np.random.rand(4,4)

array([[0.60607862, 0.23278408, 0.05375809, 0.40491423],
       [0.76652868, 0.32717849, 0.88723371, 0.56584339],
       [0.22929637, 0.36449277, 0.73700533, 0.31203655],
       [0.40593124, 0.07915716, 0.35447563, 0.29279521]])

# randn

In [30]:
#it generate normal distribution (n-normal ) it gives negative or positive values
np.random.randn(4)

array([-0.02197819,  1.84084239,  1.05396729,  0.93025853])

In [31]:
np.random.randn(4,4)

array([[ 0.26838748,  0.33417786,  0.57144423,  1.44293359],
       [ 1.22334844, -0.39518718, -0.61366019,  0.7914089 ],
       [ 0.79215709,  0.00614052,  0.35478411,  0.07048447],
       [ 0.03637222, -2.66199399,  0.49586825, -0.15114299]])

# randint

In [32]:
#it give integer but we have to give range not give float values
np.random.randint(1,100)

84

In [33]:
np.random.randint(1,100,5)

array([ 9, 89, 55, 26, 40])

In [34]:
np.linspace(1,8,4)

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [35]:
np.random.randint(1,8,4)

array([5, 5, 5, 7])

In [36]:
np.random.randint(2,9,4)

array([2, 6, 4, 7])

# Array Distribute and method
# shape

In [37]:
array1=np.arange(20)
random_arr=np.random.randint(1,50,10)

In [38]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
array1.shape

(20,)

In [40]:
random_arr

array([18, 34, 42, 23, 36, 30, 12, 21, 35, 13])

In [41]:
random_arr.shape

(10,)

# Reshape

In [42]:
# change its original shape
arr1=array1.reshape(2,10)

In [43]:
arr1.shape[0]   #index number

2

In [44]:
ar=np.arange(8) 
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
ar.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
ar.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [47]:
ar.reshape(8,-1) # 1st element stands for rowa ND 2ND COL

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [48]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [49]:
arr.max()

19

In [50]:
arr.min()

1

In [51]:
arr.argmax()    # it gives indices number max value

18

In [52]:
arr.argmin()  # it gives index number of min value

0

In [53]:
array1.reshape(1,20).shape #reshape

(1, 20)

# dtype

In [54]:
arr.dtype

dtype('int32')

In [55]:
np.result_type(arr)

dtype('int32')

In [56]:
array2=np.arange(0,10,1.22,dtype=np.int32)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
array3=np.arange(0,10,1,dtype=np.float64)
array3

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
array4=np.arange(0,10,2,dtype=np.complex64)
array4

array([0.+0.j, 2.+0.j, 4.+0.j, 6.+0.j, 8.+0.j], dtype=complex64)

In [59]:
type(array1)

numpy.ndarray

In [60]:
type(array2)

numpy.ndarray