In [2]:
import numpy as np
arr=np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

In [3]:
arr+arr

array([ 0,  2,  4,  6,  8, 10])

In [4]:
arr-arr


array([0, 0, 0, 0, 0, 0])

In [5]:
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
arr*arr

array([ 0,  1,  4,  9, 16, 25])

In [7]:
arr**arr

array([   1,    1,    4,   27,  256, 3125], dtype=int32)

In [8]:
arr/arr


C:\Users\SAURABH TUNGAR\AppData\Local\Temp\ipykernel_15172\3576909265.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.])

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

# some universal Array function

In [11]:
np.sort(arr)

array([0, 1, 2, 3, 4, 5])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [15]:
np.exp(arr) #exponential (^)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427])

In [17]:
np.log(arr)

C:\Users\SAURABH TUNGAR\AppData\Local\Temp\ipykernel_15172\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791])